Initial files for debian package

diff --git a/bin/paraFoam b/bin/paraFoam
--- a/bin/paraFoam
+++ b/bin/paraFoam
@@ -1,133 +1,148 @@
 #!/bin/sh
-#------------------------------------------------------------------------------
-# =========                 |
-# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
-#  \\    /   O peration     |
-#   \\  /    A nd           | Copyright held by original author
-#    \\/     M anipulation  |
-#-------------------------------------------------------------------------------
-# License
-#     This file is part of OpenFOAM.
 #
-#     OpenFOAM is free software; you can redistribute it and/or modify it
-#     under the terms of the GNU General Public License as published by the
-#     Free Software Foundation; either version 2 of the License, or (at your
-#     option) any later version.
+# Copyright (c) 2008-2009 Takuya OSHIMA <oshima@eng.niigata-u.ac.jp>.
+# All rights reserved.
 #
-#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
-#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
-#     for more details.
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
 #
-#     You should have received a copy of the GNU General Public License
-#     along with OpenFOAM; if not, write to the Free Software Foundation,
-#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
+#  * Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+#  * Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the
+#    distribution.
+#
+#  * Neither the name of the author nor the names of any contributors
+#    may be used to endorse or promote products derived from this
+#    software without specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR
+# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
+# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
+# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
+# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
+# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 # Script
-#     paraFoam
+#     pvFoam
 #
 # Description
-#     start paraview with the OpenFOAM libraries
-#
-#------------------------------------------------------------------------------
-usage() {
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-    cat<<USAGE
+#     ParaView interface script for use with vtkPOpenFOAMReader.
 
-usage: ${0##*/} [OPTION]
-options:
-  -case   dir    specify alternative case directory
-  -region name   specify mesh region name
-  -touch         only create the .OpenFOAM file
+# Adjust as necessary.
+# You might also want to set LD_LIBRARY_PATH or DYLD_LIBRARY_PATH.
+paraviewPath="`which paraview`"
+# or in full path like paraviewPath=/opt/ParaView3/bin/paraview
 
-* start paraview $ParaView_VERSION with the OpenFOAM libraries
-
-USAGE
+if [ ! -x "${paraviewPath}" -o -d "${paraviewPath}" ]; then
+    # not using LINENO which is not supported by dash (yet)
+    echo "ParaView not found; set paraviewPath at line" `awk '/paraviewPath/{print FNR;exit 0}' $0` "of $0."
     exit 1
-}
+fi
 
-unset regionName touchOnly
+ext=foam
+casePath=.
+script=${0##*/}
+background=yes
+trapCommand=trap
 
-# parse options
-while [ "$#" -gt 0 ]
+while [ $# -gt 0 ]
 do
     case "$1" in
-    -h | -help)
-        usage
-        ;;
-    -case)
-        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-        cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
-        shift 2
-        ;;
-    -region)
-        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-        regionName=$2
-        shift 2
-        ;;
-    -touch)
-        touchOnly=true
-        shift
-        ;;
-    *)
-        usage "unknown option/argument: '$*'"
-        ;;
+	-case)
+	    if [ $# -lt 2 ]; then
+		echo "-case requires path specification"
+		exit 1
+	    fi
+	    shift
+	    casePath="$1"
+	    ;;
+	-clientServer|-cs)
+	    if [ $# -lt 2 ]; then
+		echo "-clientServer or -cs requires specification of the server resource name"
+		exit 1
+	    fi
+	    shift
+	    csResourceName="$1"
+	    ;;
+	-foreground|-fg)
+	    background=no
+	    ;;
+	-keepStub|-ks)
+	    trapCommand=:
+	    ;;
+	-help)
+	    echo "Usage: ${script} [-case <dir>] [-clientServer|-cs <server resource name>] [-foreground|-fg] [-keepStub|-ks] [-help]"
+	    exit 0
+	    ;;
     esac
+    shift
 done
 
-# get a sensible caseName
-caseName=${PWD##*/}
-caseFile="$caseName.OpenFOAM"
-fvControls="system"
-
-if [ -n "$regionName" ]
-then
-    caseFile="$caseName{$regionName}.OpenFOAM"
-    fvControls="$fvControls/$regionName"
+# cd to the case directory
+if ! cd "${casePath}" > /dev/null 2>&1; then
+    echo "Cannot change directory to \"${casePath}\"; exiting"
+    exit 1
 fi
 
-if [ -n "$touchOnly" ]
-then
-    touch "$caseFile"
-    echo "created '$caseFile'"
-    exit 0
+caseName="${PWD##*/}"
+
+# see if caseName starts with controlDict or the case is in the root directory.
+if [ "${caseName#controlDict}" != "${caseName}" -o ! "${caseName}" ]; then
+    # Use case.foam as file name given to ParaView
+    caseName="case"
 fi
 
-# parent directory for normal or parallel results
-case "$caseName" in
-    processor*) parentDir=".." ;;
-    *)          parentDir="."  ;;
-esac
+fileName="${caseName}.${ext}"
+if [ -e "${fileName}" ]; then
+    if [ ! -r "${fileName}" ]; then
+	echo "Stub ${fileName} exists but not readable; exiting"
+	exit 1
+    fi
+    trapCommand=:
+else
+    if ! touch "${fileName}" > /dev/null 2>&1; then
+	echo "Cannot create stub ${fileName}; exiting"
+	exit 1
+    fi
+fi
 
-# check existence of essential files
-for check in system/controlDict $fvControls/fvSchemes $fvControls/fvSolution
-do
-    [ -s "$parentDir/$check" ] || usage "file does not exist:  '$parentDir/$check'"
-done
+# set the locale where ParaView is run under to "C" so that the
+# interpretation of decimal points by the system routines are not
+# affected
+export LANG=C
+export LC_ALL=C
 
+# specify fileName with full path so that it can easily be accessed
+# later with File->Recent Files
+if [ "${background}" = "yes" ]; then
+    (
+	${trapCommand} "rm -f \"${fileName}\" ; exit 0" \
+	    EXIT HUP INT PIPE ALRM TERM USR1 USR2 ;
+	if [ "${csResourceName}" ]; then
+	    "${paraviewPath}" --data="${PWD}/${fileName}" \
+		--server="${csResourceName}"
+	else
+	    "${paraviewPath}" --data="${PWD}/${fileName}"
+	fi
+    ) &
+else
+    ${trapCommand} "rm -f \"${fileName}\" ; exit 0" \
+	EXIT HUP INT PIPE ALRM TERM USR1 USR2
+    if [ "${csResourceName}" ]; then
+	"${paraviewPath}" --data="${PWD}/${fileName}" \
+	    --server="${csResourceName}"
+    else
+	"${paraviewPath}" --data="${PWD}/${fileName}"
+    fi
+fi
 
-case "$ParaView_VERSION" in
-2*)
-    trap "rm -f paraFoam.pvs $caseFile 2>/dev/null; exit 0" EXIT TERM INT
-    touch "$caseFile"
-
-    # since we are now in the cwd, %CASE% is '$PWD/$caseFile'
-    sed -e s@%CASE%@$PWD/$caseFile@g \
-        $WM_PROJECT_DIR/bin/tools/paraFoam.pvs > paraFoam.pvs
-
-    paraview paraFoam.pvs
-    ;;
-
-*)
-    # only create/remove caseFile if it didn't already exist
-    [ -e $caseFile ] || {
-        trap "rm -f $caseFile 2>/dev/null; exit 0" EXIT TERM INT
-        touch "$caseFile"
-        echo "created temporary '$caseFile'"
-    }
-
-    paraview --data="$caseFile"
-    ;;
-
-esac
 #------------------------------------------------------------------------------
