bin/tools/RunFunctions: verbose_report_on_runApplication_error will exit on error

diff --git a/bin/tools/RunFunctions b/bin/tools/RunFunctions
--- a/bin/tools/RunFunctions
+++ b/bin/tools/RunFunctions
@@ -140,18 +140,23 @@ makeFsiResultsLinks ()
 # Can be overriden by the calling script
 : ${DUMP_NBR_LOG_LINES:=10}; export DUMP_NBR_LOG_LINES
 
-# Exception handler: dump the tail of the log file on error
+# Exception handler: dump the tail of the log file on error and exit
 verbose_report_on_runApplication_error()
 {
-    if [ "$reportOnErrorOnlyOnce" ] ; then
-        echo "Error running $APP_RUN..."
-        if [ -f $LOG_NAME ] ; then
-            tail -n $DUMP_NBR_LOG_LINES $LOG_NAME
-        fi
-    fi
+   ecode=$?
+   if [ "$reportOnErrorOnlyOnce" ] ; then
+       echo " "
+       echo " => Error running $APP_RUN..."
+       if [ -f $LOG_NAME ] ; then
+	   echo " => Here are the last $DUMP_NBR_LOG_LINES lines of the log file $LOG_NAME..."
+	   echo " "
+           tail -n $DUMP_NBR_LOG_LINES $LOG_NAME
+           exit $ecode;
+       fi
+   fi
 
-    # Do not report again when exiting
-    unset reportOnErrorOnlyOnce
+   # Do not report again when exiting
+   unset reportOnErrorOnlyOnce
 }
 
 # Variation of runApplication with exception handling
